global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Tell Prometheus where Alertmanager lives (inside the "monitor" network)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alerting rules from the mounted rules directory
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # External availability/latency checks via Blackbox
  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:5000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Host metrics (node_exporter)
  - job_name: "node"
    static_configs:
      - targets:
          - host.docker.internal:9100
