
name: Task CD (Main Deploy)
on:
  push:
    branches:
      - 'main'

jobs:
  cd-build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t codeislife771/flask-task-manager:${{ github.sha }} .
    
    # Login step (only on push to main)
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN_RUN }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Push image (commit SHA)
      if: github.ref == 'refs/heads/main'
      run: docker push codeislife771/flask-task-manager:${{ github.sha }}

    - name: Tag & push latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag codeislife771/flask-task-manager:${{ github.sha }} codeislife771/flask-task-manager:latest
        docker push codeislife771/flask-task-manager:latest