jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Restore tfstate (all actions)
        uses: actions/download-artifact@v4
        with:
          name: tfstate
          path: terraform
        continue-on-error: true

      # --- K8s cleanup (destroy only) ---
      - name: Install kubectl (only for destroy)
        if: inputs.action == 'destroy'
        uses: azure/setup-kubectl@v4

      - name: Connect kubectl to EKS (only for destroy)
        if: inputs.action == 'destroy'
        run: aws eks update-kubeconfig --name "${{ vars.EKS_CLUSTER_NAME }}" --region "${{ vars.AWS_REGION }}"

      - name: Undeploy app (only for destroy)
        if: inputs.action == 'destroy'
        run: |
          kubectl delete service flask-service --ignore-not-found
          sleep 20
          kubectl delete -f deploy/ --ignore-not-found
          kubectl get svc -A | (grep LoadBalancer || true)
      # --- end K8s cleanup ---

      # Terraform steps (run inside terraform/)
      - name: terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: terraform plan
        if: inputs.action == 'plan'
        working-directory: terraform
        run: terraform plan -input=false

      - name: terraform apply
        if: inputs.action == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve -input=false

      - name: terraform destroy
        if: inputs.action == 'destroy'
        working-directory: terraform
        run: terraform destroy -auto-approve -input=false

      - name: Save tfstate (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: |
            terraform/terraform.tfstate
            terraform/terraform.tfstate.backup
          if-no-files-found: ignore
          retention-days: 14
