name: Infra (Plan/Apply/Destroy)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "What to run"
        required: true
        type: choice
        options: [plan, apply, destroy]
        default: plan
      dir:
        description: "Terraform working directory"
        required: false
        default: terraform

permissions:
  contents: read
  actions: read

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Quick check for terraform.tfstate (before downloading)
      - name: Verify local tfstate presence
        working-directory: ${{ github.event.inputs.dir }}
        run: |
          echo "Listing files in $(pwd):"
          ls -la || true
          if [ -f "terraform.tfstate" ]; then
            echo "Found local terraform.tfstate"
            terraform state list || true
          else
            echo "No local terraform.tfstate (will try to download artifact next)."
          fi

      # --- K8s cleanup (destroy only) ---
      - name: Install kubectl (only for destroy)
        if: ${{ always() && github.event.inputs.action == 'destroy' }}
        uses: azure/setup-kubectl@v4

      - name: Connect kubectl to EKS (only for destroy)
        if: ${{ always() && github.event.inputs.action == 'destroy' }}
        run: |
          set -e
          aws eks update-kubeconfig --name "${{ vars.EKS_CLUSTER_NAME }}" --region "${{ vars.AWS_REGION }}"

      - name: Undeploy app (only for destroy)
        if: ${{ always() && github.event.inputs.action == 'destroy' }}
        run: |
          set +e
          kubectl delete service flask-service --ignore-not-found
          sleep 15
          if [ -d "deploy" ]; then
            kubectl delete -f deploy/ --ignore-not-found
          else
            echo "deploy/ not found at repo root; skipping kubectl delete -f deploy/"
          fi
          kubectl get svc -A 2>/dev/null | (grep LoadBalancer || true)
          set -e
      # --- end K8s cleanup ---

      - name: Download previous tfstate (if exists)
        uses: actions/download-artifact@v4
        with:
          name: tfstate
          path: ${{ github.event.inputs.dir }}
        continue-on-error: true

      # Verify downloaded state
      - name: Show Terraform state after artifact download
        working-directory: ${{ github.event.inputs.dir }}
        run: |
          if [ -f "terraform.tfstate" ]; then
            echo "Restored terraform.tfstate from artifact:"
            terraform state list || true
          else
            echo "No terraform.tfstate found after download (first run or artifact missing)."
          fi

      # Terraform steps
      - name: terraform init
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform init -input=false

      - name: terraform plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform plan -input=false

      - name: terraform apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform apply -auto-approve -input=false

      - name: terraform destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform destroy -auto-approve -input=false

      # Always upload tfstate
      - name: Save tfstate (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: |
            ${{ github.event.inputs.dir }}/terraform.tfstate
