name: Infra (Plan/Apply/Destroy)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "What to run"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
      dir:
        description: "Terraform working directory"
        required: false
        default: terraform

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Restore tfstate (from previous run) using dawidd6 action (can fetch from past runs)
      - name: Restore tfstate (from previous run)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "Infra (Plan/Apply/Destroy)"   # exact name of the workflow that produced the artifact
          name: tfstate                            # artifact name to fetch
          branch: main                             # branch where the artifact was produced (adjust if needed)
          path: ${{ github.event.inputs.dir }}     # extract into the TF working dir
        continue-on-error: true

      # Quick check to see if terraform.tfstate exists and is readable
      - name: Verify tfstate presence
        working-directory: ${{ github.event.inputs.dir }}
        run: |
          echo "Listing files in $(pwd):"
          ls -la || true
          if [ -f "terraform.tfstate" ]; then
            echo "Found terraform.tfstate"
            echo "terraform state list (if backend is local):"
            terraform state list || true
          else
            echo "terraform.tfstate NOT found (destroy may find nothing to do unless using remote backend)."
          fi

      # --- K8s cleanup (destroy only) ---
      - name: Install kubectl (only for destroy)
        if: ${{ github.event.inputs.action == 'destroy' }}
        uses: azure/setup-kubectl@v4

      - name: Connect kubectl to EKS (only for destroy)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          set -e
          aws eks update-kubeconfig --name "${{ vars.EKS_CLUSTER_NAME }}" --region "${{ vars.AWS_REGION }}"

      - name: Undeploy app (only for destroy)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          # If the cluster/context does not exist, skip gracefully
          set +e
          kubectl delete service flask-service --ignore-not-found
          sleep 15
          if [ -d "deploy" ]; then
            kubectl delete -f deploy/ --ignore-not-found
          else
            echo "deploy/ not found at repo root; skipping kubectl delete -f deploy/"
          fi
          kubectl get svc -A 2>/dev/null | (grep LoadBalancer || true)
          set -e
      # --- end K8s cleanup ---

      # Terraform steps (run inside selected dir)
      - name: terraform init
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform init -input=false

      - name: terraform plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform plan -input=false

      - name: terraform apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform apply -auto-approve -input=false

      - name: terraform destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ${{ github.event.inputs.dir }}
        run: terraform destroy -auto-approve -input=false

      # Always save tfstate at the end so the next run has continuity
      - name: Save tfstate (always)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: |
            ${{ github.event.inputs.dir }}/terraform.tfstate
            ${{ github.event.inputs.dir }}/terraform.tfstate.backup
          if-no-files-found: ignore
          retention-days: 14
