name: Infra (Plan/Apply/Destroy)

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options: [plan, apply, destroy]
        default: plan
      dir:
        default: terraform

jobs:
  tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - uses: actions/checkout@v4

      # Configure AWS credentials for the job
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      # Always try to restore tfstate at the start (plan/apply/destroy).
      # If no artifact exists yet (first run), don't fail the job.
      - name: Restore tfstate (all actions)
        uses: actions/download-artifact@v4
        with:
          name: tfstate
          path: ${{ inputs.dir }}
        continue-on-error: true

      # --- Simple Kubernetes cleanup before Terraform destroy ---
      # Optional cleanup before destroy: remove K8s resources that may hold AWS LBs/ENIs
      - name: Install kubectl (only for destroy)
        if: inputs.action == 'destroy'
        uses: azure/setup-kubectl@v4

      - name: Connect kubectl to EKS (only for destroy)
        if: inputs.action == 'destroy'
        run: |
          aws eks update-kubeconfig --name "${{ vars.EKS_CLUSTER_NAME }}" --region "${{ vars.AWS_REGION }}"

      - name: Undeploy app (only for destroy)
        if: inputs.action == 'destroy'
        run: |
          kubectl delete service flask-service --ignore-not-found
          sleep 20
          kubectl delete -f deploy/ --ignore-not-found
          kubectl get svc -A | (grep LoadBalancer || true)
      # --- end of Kubernetes cleanup ---

      # Terraform workflow
      - name: terraform init
        run: terraform init -input=false

      - name: terraform plan
        if: inputs.action == 'plan'
        run: terraform plan -input=false

      - name: terraform apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false

      - name: terraform destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve -input=false

      # Always save tfstate at the end (even on failure) so next run has continuity.
      - name: Save tfstate (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfstate
          path: |
            ${{ inputs.dir }}/terraform.tfstate
            ${{ inputs.dir }}/terraform.tfstate.backup
          if-no-files-found: ignore
          retention-days: 14
